version: '3.8'

services:
  alparbot:
    build:
      context: .
      dockerfile: Dockerfile.hardcoded
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - alparbot-network

networks:
  alparbot-network:
    driver: bridge
